version: '3.8'

services:
  # Backend Service (FastAPI)
  core_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "core_api"
    ports:
      - "8000:8000"
    working_dir: /app
    networks:
      - pesabu-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PYTHONPATH=/app

networks:
  pesabu-network:
    driver: bridge

volumes:
  pesabu_backend_data: